# SPDX-FileCopyrightText: Copyright 2026 citron Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

# Turns the IPS patches in a directory into a C++ include of byte arrays, so the emulator can apply
# the exact files a console applies through Atmosphere (see core/file_sys/private_server_patches.cpp)
# without shipping them as loose files or hand-copying their bytes into source.
#
# Every file must be named <category>.<BUILD_ID>.ips, where BUILD_ID is the build id of the
# executable the patch is for, in hex. The generated include defines one `constexpr u8 PatchDataN[]`
# per file and a `kEmbeddedPatches` initialiser list of {category, build_id, bytes} entries; the
# including file supplies the struct they initialise.
#
#   generate_private_server_patches(<ips directory> <output file>)
#
# Re-runs CMake when a patch file changes, and leaves the output untouched when its content has not
# changed, so editing nothing never rebuilds core.

function(generate_private_server_patches ips_dir output)
    file(GLOB ips_files CONFIGURE_DEPENDS "${ips_dir}/*.ips")
    list(SORT ips_files)

    # An empty directory would build fine and silently ship no patches, which for Splatoon 3 means
    # a game that sits on "connecting" forever. Refuse it here instead.
    if(NOT ips_files)
        message(FATAL_ERROR "generate_private_server_patches: no .ips files in ${ips_dir}")
    endif()

    set(arrays "")
    set(table "")
    set(index 0)
    foreach(path IN LISTS ips_files)
        get_filename_component(name "${path}" NAME)
        if(NOT name MATCHES "^([a-z0-9_]+)\\.([0-9A-Fa-f]+)\\.ips$")
            message(FATAL_ERROR
                "generate_private_server_patches: '${name}' is not named <category>.<build id>.ips")
        endif()
        set(category "${CMAKE_MATCH_1}")
        string(TOUPPER "${CMAKE_MATCH_2}" build_id)

        file(READ "${path}" hex HEX)
        if(hex STREQUAL "")
            message(FATAL_ERROR "generate_private_server_patches: '${name}' is empty")
        endif()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")

        string(APPEND arrays "// ${name}\nconstexpr u8 PatchData${index}[] = {${bytes}};\n")
        string(APPEND table "    {\"${category}\", \"${build_id}\", PatchData${index}},\n")
        math(EXPR index "${index}+1")

        # CONFIGURE_DEPENDS on the glob catches files being added or removed; this catches one being
        # edited in place.
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    endforeach()

    # One quoted argument, never re-expanded unquoted: CMake would split the result on every ';',
    # which is exactly what ends each C++ statement here.
    set(content "// Generated by CMake from the .ips files in ${ips_dir}. Do not edit.\n\n${arrays}\nconstexpr EmbeddedPatch kEmbeddedPatches[] = {\n${table}};\n")

    set(existing "")
    if(EXISTS "${output}")
        file(READ "${output}" existing)
    endif()
    if(NOT existing STREQUAL content)
        get_filename_component(output_dir "${output}" DIRECTORY)
        file(MAKE_DIRECTORY "${output_dir}")
        file(WRITE "${output}" "${content}")
    endif()
endfunction()
