#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Assemble hypervisor_el1.S and regenerate src/core/arm/hypervisor/hypervisor_el1.inc."""
import os, shutil, struct, subprocess, sys, tempfile

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(os.path.dirname(here))
source = os.path.join(here, "hypervisor_el1.S")
output = os.path.join(root, "src", "core", "arm", "hypervisor", "hypervisor_el1.inc")
prefix = next((p for p in ("aarch64-linux-gnu-", "aarch64-elf-", "aarch64-none-elf-", "")
               if shutil.which(p + "as") and shutil.which(p + "objcopy")), None)
if prefix is None:
    sys.exit("An AArch64 GNU assembler and objcopy are required")
with tempfile.TemporaryDirectory() as tmp:
    obj, binary = os.path.join(tmp, "el1.o"), os.path.join(tmp, "el1.bin")
    subprocess.check_call([prefix + "as", source, "-o", obj])
    subprocess.check_call([prefix + "objcopy", "-O", "binary", obj, binary])
    data = open(binary, "rb").read()

def words(lo, hi):
    seg = data[lo:hi].rstrip(b"\0")
    seg += b"\0" * (-len(seg) % 4)
    return struct.unpack("<%dI" % (len(seg) // 4), seg)

def table(name, values):
    lines = [f"constexpr uint32_t {name}[] = {{"]
    for i in range(0, len(values), 6):
        lines.append("    " + ", ".join(f"0x{v:08x}" for v in values[i:i + 6]) + ",")
    return "\n".join(lines + ["};", ""])

text = "\n".join([
    "// SPDX-License-Identifier: GPL-2.0-or-later",
    "// Generated by tools/macos/gen_hypervisor_el1.py from tools/macos/hypervisor_el1.S.",
    "// Do not edit by hand; regenerate with an AArch64 GNU assembler.",
    "#pragma once",
    "#include <cstdint>",
    "// Kernel page 1: EL1 vector table (VBAR) plus helpers at +0x800.",
    table("kEl1VectorPage", words(0, 0x1000)),
    "// Kernel page 2: entry stubs (+0x00 clrex, +0x10 TLB, +0x30 TLB+IC, +0x50 counter probe).",
    table("kEl1StubPage", words(0x1000, 0x2000)),
])
open(output, "w").write(text)
print("Wrote", output)
